In [37]:
import pyrealsense2 as rs
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import matplotlib.patches as patches
import capture
import cv2

color_image,depth_image,depth_scale,intrinsics,file_name = capture.capture(True)
print(file_name)


color_20190519T082149.png


In [36]:
import matplotlib.image as mpimg
import numpy as np
import cv2

image = cv2.imread("/tf/logs_test_img/color_20190518T071146-Copy1.png")

lower_red = np.array([110, 110, 110])
upper_red = np.array([130, 130, 130])

print(image.shape)
mat1 = image[:,:,1] > 100
# mat2 = image[:,:,0] > 0
mat3 = image[:,:,0] > 100
image[mat1] = [0,0,0]
# image[mat2] = 0
# handled_image = cv2.cvtColor(mask_image, cv2.COLOR_HSV2BGR)

# cv2.imwrite('/tf/logs/color_20190519T025237_test_hsv.png', hsv)
cv2.imwrite('/tf/logs_test_img/color_20190518T071146-Copy1-test.png', image)

(720, 1280, 3)


True

In [12]:
import numpy as np

a = np.zeros((2,2))
b = np.array([1,2,4,5]).reshape(2,2)
b2 = np.array([4,1,2,7]).reshape(2,2)
c = [a, b,b2]
d = np.array(c)
print(d)
np.median(c, axis=0)

[[[0. 0.]
  [0. 0.]]

 [[1. 2.]
  [4. 5.]]

 [[4. 1.]
  [2. 7.]]]


array([[1., 1.],
       [2., 5.]])